default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gopi
  password: fr33d0m
  host: localhost

development:
  <<: *default
  database: propmaticly_development

test:
  <<: *default
  database: propmaticly_test

production:
  <<: *default
  host: propmaticly-production.crce46og4nsn.us-east-2.rds.amazonaws.com
  database: propmaticly_production
  username: gopi
  password: fr33d0m2025
