default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: gopi
  password: fr33d0m
  host: localhost

development:
  <<: *default
  database: propmatically_development

test:
  <<: *default
  database: propmatically_test

production:
  <<: *default
  database: propmatically_production
  username: gopi
  password: <%= ENV['DATABASE_PASSWORD'] %>
