# frozen_string_literal: "1"

InspectionRules::InspectionRule.upsert({ compliance_item: :bed_bug, frequency_in_months: 12, fixed_day_month: { day: 31, month: 12}, numerical_properties: { number_of_residential_units: { operator: '>=', value: 3 } }, description: 'Annual Bed Bug Inspection Report is a requirement to document bed bug infestations and inspection outcomes. Building owners of certain residential properties report on bed bug infestations annually. The report is required for multi-family residential buildings (buildings with three or more units).'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :cooling_tower, frequency_in_months: 12, fixed_day_month: { day: 1, month: 11}, has_properties: { cooling_tower: true }, description: 'Monthly Cooling Tower Inspection Report focuses on maintaining water quality and controlling Legionella growth by monitoring chemical levels and general system conditions.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :energy_benchmarking, frequency_in_months: 12, fixed_day_month: { day: 1, month: 5}, numerical_properties: { square_feet: { operator: '>', value: 25_000 } }, description: 'Local Laws 84 and 133 mandate that building owners annually report their properties energy and water consumption to promote transparency and encourage energy efficiency.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :drinking_water_storage_tank, frequency_in_months: 12, fixed_day_month: { day: 15, month: 1}, has_properties: { drinking_water_storage_tank: true }, description: 'building owners with drinking water storage tanks are required to conduct annual inspections and file the results with the Department of Health and Mental Hygiene (DOHMH). This mandate aims to ensure the safety and cleanliness of the citys drinking water supply.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :greenhouse_gas_emissions, frequency_in_months: 12, fixed_day_month: { day: 1, month: 5}, numerical_properties: { square_feet: { operator: '>', value: 25_000 } }, description: 'Local Law 97 (LL97), building owners are required to monitor and report their properties greenhouse gas (GHG) emissions to ensure compliance with established emissions limits.'}, unique_by: :compliance_item)
InspectionRules::EnergyAuditsRetroCommissioning.upsert({ compliance_item: :energy_audits_retro_commissioning, frequency_in_months: 120, fixed_day_month: { day: 31, month: 12}, numerical_properties: { square_feet: { operator: '>=', value: 50_000 } }, description: 'Energy Efficiency Ratings (LL87) involves conducting comprehensive energy audits and retro-commissioning for buildings, documenting findings and recommendations to improve energy efficiency.'}, unique_by: :compliance_item)

InspectionRules::InspectionRule.upsert({ compliance_item: :low_pressure_boiler, frequency_in_months: 12, fixed_day_month: { day: 31, month: 12}, has_properties: { low_pressure_boiler: true }, description: 'Low Pressure Boiler Inspection focuses on the overall condition and safety of the boiler, including checks for leaks, proper functioning of controls, and the integrity of safety devices.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :high_pressure_boiler_internal, frequency_in_months: 12, fixed_day_month: { day: 30, month: 6}, has_properties: { high_pressure_boiler: true }, description: 'High Pressure Boilers must have an internal inspection. These inspections must be conducted within the same cycle but should be performed approximately six months apart.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :high_pressure_boiler_external, frequency_in_months: 12, fixed_day_month: { day: 31, month: 12}, has_properties: { high_pressure_boiler: true }, description: 'High Pressure Boilers must have an external inspection. These inspections must be conducted within the same cycle but should be performed approximately six months apart.'}, unique_by: :compliance_item)

InspectionRules::InspectionRule.upsert({ compliance_item: :elevator_periodic, frequency_in_months: 12, fixed_day_month: { day: 31, month: 12}, has_properties: { elevator: true }, description: 'These inspections serve as routine checks to ensure ongoing compliance with safety standards and are distinct from the Cat-1 and Cat-5 tests.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :elevator_cat_1, based_on_last_inspection: true, frequency_in_months: 12, has_properties: { elevator: true }, description: 'Category One (Cat-1) Elevator Inspection Report is an annual inspection requirement for all elevators and similar devices, such as escalators and other lifting devices. This inspection ensures elevators comply with safety standards and regulations.'}, unique_by: :compliance_item)
# InspectionRules::InspectionRule.upsert({ compliance_item: :elevator_cat_3, based_on_last_inspection: true, frequency_in_months: 36, has_properties: { hydraulic_elevator: true }, description: 'Category Three (Cat-3) elevator inspection specifically required for water hydraulic elevators. This inspection ensures that hydraulic systems in these elevators are functioning safely, as hydraulic elevators operate differently than traction (cable-driven) elevators and require specialized attention.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :elevator_cat_5, based_on_last_inspection: true, frequency_in_months: 60, has_properties: { elevator: true }, description: 'Category Five (CAT5) elevator inspection is a comprehensive safety test mandated to ensure the safe operation of elevators. This inspection involves testing the elevator at its rated load and speed to verify that all safety mechanisms function correctly under full operational conditions.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :backflow_prevention, based_on_last_inspection: true, frequency_in_months: 12, has_properties: { backflow: true }, description: 'Backflow Prevention Inspection Report is required for buildings with backflow prevention devices. These devices prevent contaminated water from flowing back into the public water supply, ensuring the safety of drinking water.'}, unique_by: :compliance_item)

InspectionRules::InspectionRule.upsert({ compliance_item: :sprinkler_system, based_on_last_inspection: true, frequency_in_months: 60, has_properties: { sprinkler_system: true }, description: '5-Year sprinkler system inspection is a thorough check of the internal condition of the sprinkler piping to detect any corrosion, blockages, or other issues that could hinder water flow.'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :standpipe_system, based_on_last_inspection: true, frequency_in_months: 60, has_properties: { standpipe: true }, description: '5-Year Standpipe System inspection is an in-depth evaluation of the internal and operational condition of the standpipe system. This inspection aims to identify hidden issues, such as internal corrosion or obstructions, that could impair water flow during a fire.'}, unique_by: :compliance_item)
# InspectionRules::InspectionRule.upsert({ compliance_item: :annual_property_registration, frequency_in_months: 12, numerical_properties: { }, description: 'The registration helps the NYC Department of Housing Preservation and Development (HPD) maintain an updated database of property ownership and ensures compliance with housing regulations.'}, unique_by: :compliance_item)

parking_cycle_schedule = [{ "borough_code": [1], "community_district_number": [1, 2, 3, 4, 5, 6, 7], "end_date": "2023-12-31" },
                          { "borough_code": [1], "community_district_number": [8, 9, 10, 11, 12], "end_date": "2025-12-31" },
                          { "borough_code": [3], "community_district_number": "all", "end_date": "2025-12-31" },
                          { "borough_code": [2, 4, 5], "community_district_number": "all", "end_date": "2027-12-31" }]

gas_piping_cycle_schedule = [{ "borough_code": "all", "community_district_number": [1, 3, 10], "end_date": "2024-12-31" },
                             { "borough_code": "all", "community_district_number": [2, 5, 7, 13, 18], "end_date": "2025-12-31" },
                             { "borough_code": "all", "community_district_number": [4, 6, 8, 9, 16], "end_date": "2026-12-31" },
                             { "borough_code": "all", "community_district_number": [11, 12, 14, 15, 17], "end_date": "2027-12-31" }]

facade_cycle_schedule = [{ "borough_code": "all", "tax_block_number": [4, 5, 6, 9], "end_date": "2027-2-21" },
                          { "borough_code": "all", "tax_block_number": [0, 7, 8],"end_date": "2028-2-21" },
                          { "borough_code": "all", "tax_block_number": [1, 2, 3], "end_date": "2029-2-21" }]

retaining_wall_cycle_schedule = [{ "borough_code": [1], "community_district_number": "all", "end_date": "2025-12-31" },
                                 { "borough_code": [2], "community_district_number": "all", "end_date": "2024-12-31" },
                                 { "borough_code": [3], "community_district_number": "all", "end_date": "2028-12-31" },
                                 { "borough_code": [4], "community_district_number": "all", "end_date": "2027-12-31" },
                                 { "borough_code": [5], "community_district_number": "all", "end_date": "2026-12-31" }]

InspectionRules::InspectionRule.upsert({ compliance_item: :retaining_wall, frequency_in_months: 60, cycle_schedule: retaining_wall_cycle_schedule, has_properties: { retaining_wall: true }, description: 'Local Law 37 of 2008 mandates that property owners with retaining walls meeting specific criteria conduct regular inspections to ensure public safety'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :parking_structure, frequency_in_months: 72, cycle_schedule: parking_cycle_schedule, has_properties: { parking_structure: true }, description: 'Parking Structure Inspection Report (LL126) requires owners of parking structures to have their garages inspected every six years, and to file a report with inspection results to the the Department of Buildings'}, unique_by: :compliance_item)
InspectionRules::InspectionRule.upsert({ compliance_item: :gas_piping, frequency_in_months: 48, cycle_schedule: gas_piping_cycle_schedule, has_properties: { gas_piping: true }, description: 'Gas Piping System Inspection Report (LL152) documents the findings from inspections of gas piping systems in buildings, ensuring that they are safe and in compliance with regulations.'}, unique_by: :compliance_item)
InspectionRules::Facade.upsert({ compliance_item: :facade, frequency_in_months: 60, cycle_schedule: facade_cycle_schedule, numerical_properties: { number_of_stories: { operator: '>', value: 6 } }, description: 'Facade Inspection Safety Program (FISP), formerly known as Local Law 11, requires periodic inspections of building facades to ensure safety and compliance. This applies to buildings taller than six stories.'}, unique_by: :compliance_item)